name: main

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Setup golang
      uses: actions/setup-go@v2
      with:
        go-version: '^1.19.1'
      id: go

    - name: Install shellcheck
      run: |
        mkdir /tmp/shellcheck \
        && curl -Ls "https://github.com/koalaman/shellcheck/releases/download/v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz" \
        | tar vxJf - -C /tmp/shellcheck
        echo "/tmp/shellcheck/shellcheck-v0.7.1" >> $GITHUB_PATH

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test
      run: dev/test -v

    - name: E2E Test
      run: docker run -v ${PWD}/bin:/buildpack-apt -v ${PWD}/e2e/e2e.sh:/e2e/e2e.sh ubuntu:latest /e2e/e2e.sh
